package com.trendyolclone.common.event;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("DomainEvent")
class DomainEventTest {

    @Test
    @DisplayName("should create a domain event with auto-generated eventId and timestamp")
    void shouldCreateDomainEventWithAutoGeneratedFields() {
        // given
        UUID aggregateId = UUID.randomUUID();
        String eventType = "USER_REGISTERED";
        String aggregateType = "User";
        String payload = "test-payload";

        // when
        DomainEvent<String> event = DomainEvent.of(eventType, aggregateId, aggregateType, payload);

        // then
        assertThat(event.eventId()).isNotNull();
        assertThat(event.eventType()).isEqualTo("USER_REGISTERED");
        assertThat(event.timestamp()).isNotNull();
        assertThat(event.timestamp()).isBeforeOrEqualTo(LocalDateTime.now());
        assertThat(event.aggregateId()).isEqualTo(aggregateId);
        assertThat(event.aggregateType()).isEqualTo("User");
        assertThat(event.payload()).isEqualTo("test-payload");
    }

    @Test
    @DisplayName("should generate unique eventId for each event")
    void shouldGenerateUniqueEventId() {
        // given
        UUID aggregateId = UUID.randomUUID();

        // when
        DomainEvent<String> event1 = DomainEvent.of("EVENT_A", aggregateId, "Aggregate", "payload1");
        DomainEvent<String> event2 = DomainEvent.of("EVENT_B", aggregateId, "Aggregate", "payload2");

        // then
        assertThat(event1.eventId()).isNotEqualTo(event2.eventId());
    }

    @Test
    @DisplayName("should accept complex payload types")
    void shouldAcceptComplexPayloadTypes() {
        // given
        record OrderPayload(UUID orderId, double totalAmount) {}
        UUID aggregateId = UUID.randomUUID();
        UUID orderId = UUID.randomUUID();
        OrderPayload payload = new OrderPayload(orderId, 199.99);

        // when
        DomainEvent<OrderPayload> event = DomainEvent.of("ORDER_CREATED", aggregateId, "Order", payload);

        // then
        assertThat(event.payload()).isEqualTo(payload);
        assertThat(event.payload().orderId()).isEqualTo(orderId);
        assertThat(event.payload().totalAmount()).isEqualTo(199.99);
    }

    @Test
    @DisplayName("should accept null payload")
    void shouldAcceptNullPayload() {
        // given
        UUID aggregateId = UUID.randomUUID();

        // when
        DomainEvent<Object> event = DomainEvent.of("ENTITY_DELETED", aggregateId, "Entity", null);

        // then
        assertThat(event.payload()).isNull();
        assertThat(event.eventType()).isEqualTo("ENTITY_DELETED");
        assertThat(event.aggregateId()).isEqualTo(aggregateId);
    }

    @Test
    @DisplayName("should correctly set all fields via record constructor")
    void shouldCorrectlySetAllFieldsViaConstructor() {
        // given
        UUID eventId = UUID.randomUUID();
        UUID aggregateId = UUID.randomUUID();
        LocalDateTime timestamp = LocalDateTime.of(2025, 1, 15, 10, 30, 0);

        // when
        DomainEvent<String> event = new DomainEvent<>(eventId, "TEST_EVENT", timestamp, aggregateId, "TestAggregate", "data");

        // then
        assertThat(event.eventId()).isEqualTo(eventId);
        assertThat(event.eventType()).isEqualTo("TEST_EVENT");
        assertThat(event.timestamp()).isEqualTo(timestamp);
        assertThat(event.aggregateId()).isEqualTo(aggregateId);
        assertThat(event.aggregateType()).isEqualTo("TestAggregate");
        assertThat(event.payload()).isEqualTo("data");
    }

    @Test
    @DisplayName("should set timestamp close to current time when using factory method")
    void shouldSetTimestampCloseToCurrentTime() {
        // given
        LocalDateTime before = LocalDateTime.now();
        UUID aggregateId = UUID.randomUUID();

        // when
        DomainEvent<String> event = DomainEvent.of("EVENT", aggregateId, "Type", "payload");

        // then
        LocalDateTime after = LocalDateTime.now();
        assertThat(event.timestamp()).isAfterOrEqualTo(before);
        assertThat(event.timestamp()).isBeforeOrEqualTo(after);
    }
}
